# Generated by Django 4.1.3 on 2022-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extinction', models.CharField(max_length=50)),
                ('period', models.CharField(choices=[('PERMIAN', 'Permian'), ('TRIASSIC', 'Triassic'), ('JURASSIC', 'Jurassic'), ('CRETACEOUS', 'Cretaceous'), ('PALEOGENE', 'Paleogene'), ('NEOGENE', 'Neogene'), ('QUATERNARY', 'Quaternary')], max_length=50)),
                ('taxonomy_class', models.CharField(max_length=50)),
                ('taxonomy_order', models.CharField(max_length=50)),
                ('taxonomy_family', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
