version: "3.9" 
services:
  app:  
    build: .
    volumes: 
      - .:/django
    ports: 
      - 8000:8000
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: app:django
    container_name: django_container 
    CMD: ["python" ,"manage.py", "runserver" ,"0.0.0.0:8000"]
    depends_on:
      - db
  db:
  #what image to use?
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data 
    # What env vars we need?
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
